export const START_FETCH_INDICADORES = 'START_FETCH_INDICADORES'
export const FETCH_INDICADOPRES_SUCCESS = 'FETCH_INDICADOPRES_SUCCESS'
export const FETCH_INDICADORES_ERROR = 'FETCH_INDICADORES_ERROR'

export const OBTENER_INDICADOR_EDITAR = 'OBTENER_INDICADOR_EDITAR';
export const INDICADOR_EDITADO_EXITO = 'INDICADOR_EDITADO_EXITO';
export const INDICADOR_EDITADO_ERROR = 'INDICADOR_EDITADO_ERROR';