export const START_FETCH_INDICADORES = 'START_FETCH_INDICADORES'
export const FETCH_INDICADOPRES_SUCCESS = 'FETCH_INDICADOPRES_SUCCESS'
export const FETCH_INDICADORES_ERROR = 'FETCH_INDICADORES_ERROR'